name: Linting, testing, building
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  pipeline:
    strategy:
      matrix:
        os: [ windows-2019 ]
        node-version: [ 17.x ]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - name: Staring Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install modules
        run: npm install
      - name: build project
        run: npm run build:prod
      - name: linting ts
        if: always()
        run: npm run lint:ts
      - name: linting scss
        if: always()
        run: npm run lint:scss
      - name: unit test
        if: always()
        run: npm run test:unit
      - name: screenshot test
        if: always()
        run: npm run test:ui:ci

